groups:
  - name: alert-rules
    rules:
      - alert: ExporterDown
        expr: up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          description: "Metrics exporter service for {{ $labels.job }} running on {{ $labels.instance }} has been down for more than 5 minutes."
          summary: "Exporter down (instance {{ $labels.instance }})"
      - alert: HostOutOfMemory
        expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Host out of memory (instance {{ $labels.instance }})"
          description: 'Node memory is filling up (< 10% left)\n VALUE = {{ $value }}\n LABELS: {{ $labels }}'
      - alert: HostOutOfDiskSpace
        expr: (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Host out of disk space (instance {{ $labels.instance }})"
          description: 'Disk is almost full (< 10% left)\n VALUE = {{ $value }}\n LABELS: {{ $labels }}'
      - alert: HostHighCpuLoad
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Host high CPU load (instance {{ $labels.instance }})"
          description: 'CPU load is > 80%\n VALUE = {{ $value }}\n LABELS: {{ $labels }}'
